sudo: false
language: objective-c
os: osx
osx_image: xcode10

cache:
  directories:
  - Carthage

matrix:
  include:
    - env: ACTION=test_ios12 PLATFORM=iOS
    - env: ACTION=test_ios11 PLATFORM=iOS
    - env: ACTION=test_tvos12 PLATFORM=tvOS
    - env: ACTION=test_tvos11 PLATFORM=tvOS
    - env: ACTION=test_ios_swift3 PLATFORM=iOS
    - env: ACTION=test_ios_swift4 PLATFORM=iOS
    - env: ACTION=test_tvos_swift3 PLATFORM=tvOS
    - env: ACTION=test_tvos_swift4 PLATFORM=tvOS
    - osx_image: xcode9.4
      env: ACTION=test_xcode9_ios_swift3 PLATFORM=iOS
    - osx_image: xcode9.4
      env: ACTION=test_xcode9_ios_swift4 PLATFORM=iOS
    - env: ACTION=pod_lint PLATFORM="iOS,tvOS"
    - env: ACTION=carthage_build PLATFORM="iOS,tvOS"

before_script:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --cache-builds --platform $PLATFORM

script:
  - bundle exec fastlane $ACTION

env:
  global:
    secure: Q4p3wB9NmkyDhg2tUDzGKh5l5p3i7jeETLNOxgx8FhSPLY1ef0V561OZEI2+M/qicL5IiBG6VttMm++145hvVVBGm7VZu24LNDrwvB1d5++LbCX80BwFlW7xsjT2STgag/qz9Qan10W/HOBS1ZkIYnBb3iMn9i2hQndcrENC0Ok=
